### ISSUE TITLE
Blank graph.

### ISSUE THREAD

**Issue by justaprussian** [trashhalo/logseq-graph-analysis#46] opened 2023-05-29 16:18 UTC
Obviously my part of issue #38 has a different background.

https://github.com/trashhalo/logseq-graph-analysis/assets/132163260/d39fc050-e08b-4f5d-baf9-b4dc262db495

Here's what I just did:
Virgin KDE Plasma account for userb
downloaded and started Logseq-linux-x64-0.9.8.appimage
added new graph /home/userb/logseq/
installed graph analysis 0.10.2 plugin
exit Logseq
copied assets, journals and pages from /home/usera/logseq  to /home/userb/logseq
started started Logseq-linux-x64-0.9.8.appimage
reindexed graph
started graph analysis 0.10.2 plugin
**graph remains all white and blank**

Whatever causes the plugin to remain blank, it must be stored somewhere in the files from journals or pages. 
Any special characters? Perhaps too large file (largest journal-file is 54,7 KiB)?

**Comment by heptaspirit** [comment] 2023-06-20 08:23
Me either.

logseq version: `Logseq-win-x64-0.9.9`
plugin version: `0.10.2`

Totally blank graph.

**Comment by mastercyb** [comment] 2023-08-14 12:13
me too :-(
logseq version: `osx 0.9.13`
plugin version: `0.10.2`

**Comment by mrparalon** [comment] 2023-08-14 12:53
Could someone check dev console? Maybe there are some errors? I can't reproduce it on my graph.

I tried also open official logseq docs, it works fine too

**Comment by heptaspirit** [comment] 2023-08-15 01:57
> Could someone check dev console? Maybe there are some errors? I can't reproduce it on my graph.
> 
> I tried also open official logseq docs, it works fine too

I download official docs graph and open it with my local logseq, the plugin works well.
But my own graph still blank, really weird.

logseq version: `win 0.9.13`
plugin version: `0.10.2`

**Comment by mrparalon** [comment] 2023-10-28 13:26
I hope that it should be fixed now. Could anyone from the reporters check it on latest version?

**Comment by Bohreromir** [comment] 2023-11-05 21:08
![image](https://github.com/trashhalo/logseq-graph-analysis/assets/40412303/c77548f7-b1c6-462e-a4b8-ac5bb08fcb48)
this is the output i get in the dev console

**Comment by mrparalon** [comment] 2023-11-06 19:26
This is strange. Does reindexing graph helps? 

Could you please try to install unpacked plugin from repo? If you will run the plugin using `yarn dev` it will give you better error and ability to use debugger there

**Comment by Bohreromir** [comment] 2023-11-06 20:07
reindexing fixed it :+1:

**Comment by justaprussian** [comment] 2023-11-11 06:45
0.10.6 update fixed

> I hope that it should be fixed now. Could anyone from the reporters check it on latest version?

Since 0.10.6 update all my graphs work again. Thank you so much!

**Closed** 2023-11-11 07:01 UTC
